### ISSUE TITLE
Certificat TLS (pour AWS en HTTPS)

### ISSUE THREAD

**Issue by EliottJaquierCPNV** [EliottJaquierCPNV/ScannergicBackendAPI#11]
Bonjour, le serveur est fonctionnel en mode HTTP seulement il ne manque plus qu'un certificat et l'instance sera prête!

**Une route à tester**
http://18.135.113.180/api/allergens
**Voir les logs du service dotnet**
 sudo journalctl -fu kestrel-scannergic.service
**Restart le service**
sudo systemctl restart kestrel-scannergic.service
**Config NGINX**
 sudo nano /etc/nginx/sites-available/default
**Restart NGINX**
sudo service nginx restart

**Comment by NicolasGlassey** [comment]
Bonsoir Eliott,

Après la mise à jour du dns, l'installation du certificat, la route fonctionne en https.

![image](https://user-images.githubusercontent.com/5616312/147153571-0360f475-05c0-412b-9ac1-569da7df0e49.png)

Au cas où vous rencontrez des erreurs, je pourrai restaurer l'instance AWS avant mon intervention.

Voici les sources utilisées : https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-debian-10
