### ISSUE TITLE
Problème démarrage du service (l'APPI) sur le server

### ISSUE THREAD

**Issue by Juillet-Mikael** [EliottJaquierCPNV/ScannergicBackendAPI#3]
GLASSEY Nicolas, Je suis entrain de configurer le server en suivant ce tutoriel [](https://www.c-sharpcorner.com/article/how-to-deploy-net-core-application-on-linux/)
Mais l'ors de la phase de démarrage du service (l'APPI), une erreur survient "Failed to enable unit: Unit file ScannergicAPI.service does not exist." j'ai beau vérifier mes configuration, les comparer au autres installation et chercher les erreurs possible, je ne trouve pas l'erreur. Auriez-vous une idée du problème ?

```
root@Scannergic:/var/netcore# sudo systemctl enable ScannergicAPI
Failed to enable unit: Unit file ScannergicAPI.service does not exist.
```

**Comment by NicolasGlassey** [comment]
@Juillet-Mikael 

(voilà ce que j'ai répondu hier sur Teams... d'ailleurs merci de ne pas multiplier les canaux de communication ;).

voici mes premiers retours :

* n avez vs pas trouvé une documentation officielle ms ?
* je partirai plus sur nginx que de l apache (plus simple à configurer)

D un point de vue plus debug, je chercherai de la documentation sur l erreur mentionnée.

Et faites des petits pas. D abord faire tourner l appli et la tester en local... puis tentez de l exposer via un serveur web. Cel vs aidera à cibler le problème (qui semble être au niveau de dépendences dont a besoin la dll).

Il s agit de code pré-compilé, doublr checkez les versions du framework vs version utilisée lors du build (framework cible)
