### ISSUE TITLE
Terminer la planification iceScrum

### ISSUE THREAD

**Issue by NolanEvard** [EliottJaquierCPNV/ScannergicBackendAPI#5]
Bonjour @NicolasGlassey ,

Après notre réunion d'aujourd'hui le sprint n'est toujours pas en cours. Nous ne pouvons pas bouger les tâches en to do, in progress et done. 
Pourriez-vous faire le nécessaire svp.

Meilleures salutations.

**Comment by NicolasGlassey** [comment]
@NolanEvard 

C'est -enfin- fait. Il faut vraiment que je vous livre lorsque nous sommes ensemble en projet sinon je pars d'en d'autres cours (comme vous) et je zappe la tâche.
